backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

site_url: https://givemeonedollar.netlify.app

display_url: https://givemeonedollar.netlify.app

collections:

  - name: "site"
    label: "Website"
    files:

      - label: "Homepage"
        name: "homepage"
        file: "content/homepage.yml"

        fields:

          - label: "Main headline"
            name: "headline"
            widget: "string"

          - label: "Subheadline"
            name: "subheadline"
            widget: "string"

          - label: "Dog image"
            name: "dog_image"
            widget: "image"

          - label: "Target amount"
            name: "target"
            widget: "number"
            value_type: "int"

          - label: "Elon text"
            name: "elon_text"
            widget: "string"

          - label: "Button text"
            name: "button_text"
            widget: "string"

          - label: "Small note"
            name: "note"
            widget: "string"
